# Generated by Django 5.0.1 on 2024-01-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_alter_user_reg_user_alter_user_reg_user_cpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_product_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='category_product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_product_price',
            field=models.IntegerField(null=True),
        ),
    ]
