# Generated by Django 5.0.1 on 2024-02-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_product_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_product_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_product_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.products'),
        ),
    ]
