# Generated by Django 5.0.1 on 2024-02-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_remove_category_category_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.products'),
        ),
    ]
