# Generated by Django 5.0 on 2024-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_orders_order_qty_orders_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
