# Generated by Django 5.0 on 2024-02-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_orders_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
    ]
