# Generated by Django 5.0 on 2024-02-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0009_remove_orders_product_id_orders_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='productid',
            new_name='product_id',
        ),
    ]
