# Generated by Django 5.0 on 2024-02-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0013_alter_orders_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
    ]
