# Generated by Django 5.0 on 2024-02-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0019_alter_orders_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pet_app.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.user_reg')),
            ],
        ),
    ]
