# Generated by Django 5.0 on 2024-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='ordered_date',
            field=models.DateField(null=True),
        ),
    ]
