# Generated by Django 5.0 on 2024-02-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0023_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
    ]
