# Generated by Django 5.0 on 2024-02-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0024_rename_product_name_products_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='product_price',
        ),
    ]
