# Generated by Django 5.0 on 2024-02-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0025_rename_name_products_product_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_desc',
            new_name='productdesc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='productimage',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='productprice',
        ),
    ]
