# Generated by Django 5.0 on 2024-02-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0026_delete_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productdesc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productimage',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productprice',
            new_name='product_price',
        ),
    ]
