# Generated by Django 5.0.1 on 2024-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0028_rename_name_products_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
