# Generated by Django 5.0.1 on 2024-03-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0029_products_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
