# Generated by Django 5.0.1 on 2024-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0032_alter_cart_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_qty',
            field=models.IntegerField(null=True),
        ),
    ]
