# Generated by Django 5.0.1 on 2024-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0033_alter_cart_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_product',
            field=models.IntegerField(default=0),
        ),
    ]
