# Generated by Django 5.0.1 on 2024-03-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0034_products_offer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_product',
            field=models.IntegerField(null=True),
        ),
    ]
