# Generated by Django 5.0.1 on 2024-03-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0036_alter_products_offer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='offer_product',
        ),
    ]
