# Generated by Django 5.0.1 on 2024-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0039_alter_user_reg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_amount',
            field=models.FloatField(),
        ),
    ]
