# Generated by Django 5.0.1 on 2024-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0040_alter_cart_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_amount',
            field=models.TextField(),
        ),
    ]
