# Generated by Django 5.0.1 on 2024-03-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0041_alter_cart_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='pet_app.user_reg'),
        ),
        migrations.AlterField(
            model_name='products',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
