# Generated by Django 5.0.1 on 2024-03-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0044_rename_product_name_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
