# Generated by Django 5.0.1 on 2024-03-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0047_orders_address_orders_city_orders_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_app.products'),
        ),
    ]
