# Generated by Django 5.0.1 on 2024-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0048_alter_orders_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_amount',
            field=models.FloatField(),
        ),
    ]
