# Generated by Django 5.0.1 on 2024-03-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0049_alter_cart_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
