# Generated by Django 5.0.1 on 2024-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0050_products_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
