# Generated by Django 5.0.1 on 2024-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0053_rename_comment_review_content_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
