# Generated by Django 5.0.1 on 2024-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0054_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='user_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='user_contry',
            field=models.TextField(null=True),
        ),
    ]
