# Generated by Django 5.0.1 on 2024-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0055_user_reg_user_dob_user_reg_user_contry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
