# Generated by Django 5.0.1 on 2024-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0056_user_reg_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
